### ISSUE TITLE
build-doxygen is not deploying the correct webpage

### ISSUE THREAD

**Issue by dstroy0** [dstroy0/InputHandler#46]
I haven't even started to dig into it, just noticed it.  I checked and the build artifacts are correct, so something is up with deployment I'm guessing.

**Comment by dstroy0** [comment]
`index.html` hasn't been updated for a month according to the commit history on the gh-pages branch, so I'll start looking for what happened around then.

**Comment by 2bndy5** [comment]
This is interesting. It seems related to [changing the workflow step to use a different action](https://github.com/dstroy0/InputHandler/commit/7f7986d38886927dd3e2031dc73316dd3437d24a).

Looking at the gh-pages branch, it seems that the doxygen output is copied to the gh-pages branch, but part of the build path remains (everything is inside the html folder). I'd guess that changing the [gh-pages settings](https://github.com/dstroy0/InputHandler/settings/pages) for this repo is the answer.
![image](https://user-images.githubusercontent.com/14963867/164850733-fa67d65f-27c8-42ac-a306-94ebb6243435.png)
Hopefully, you can select a folder named "html" from the drop-down options.

**Comment by 2bndy5** [comment]
I would argue that this a problem with [the action being used](https://github.com/JamesIves/github-pages-deploy-action). If the suggestion from my last comment isn't helpful, then you'd need to play with the action's options to make docs/html get copied to the root folder of the gh-pages branch. My guess for that would be setting
```yml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/html # The folder the action should deploy.
          target-folder: '.' # maybe try this??
```
