### ISSUE TITLE
main branch protection

### ISSUE THREAD

**Issue by dstroy0** [dstroy0/InputHandler#70]
I'm in the process of rewriting workflows for status checks, there are going to be several must pass checks to merge into main.  All the examples need to build successfully etc.  Some of these jobs have a hundred subchecks or more so I put something like this
```yml
build-adafruit:
    runs-on: ubuntu-latest
    name: build-adafruit-platforms-success
    needs:
      [
        build-lib-arduino,
        build-tool-cli-arduino,
        build-lib-pio,
        build-tool-cli-pio,
      ]
    steps:
    - name: echo
      run: echo Build Adafruit platforms success!
```
and use that as the status check to make it not insanely long
